pipeline {
    agent any
    stages {
        stage ("Build") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_HUB_USERNAME', passwordVariable: 'DOCKER_HUB_PASSWORD')]) {
                    sh 'docker build -t $DOCKER_HUB_USERNAME/delivery_exercise_1 .'
                }
            }
        }
        stage ("Push Registry") {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'DOCKER_HUB_USERNAME', passwordVariable: 'DOCKER_HUB_PASSWORD')]) {
                    sh 'docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD'
                    sh 'docker push $DOCKER_HUB_USERNAME/delivery_exercise_1'
                }
            }
        }
    }
}